// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DwarfMiningIdleGame.Server.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260425034410_ChangeTypesGuidToStrings")]
    partial class ChangeTypesGuidToStrings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("ChestDropTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChestLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChestDropTables");
                });

            modelBuilder.Entity("DwarfMiningIdleGame.Server.Entities.GameEntities.PlayerChest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChestDropTableId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChestDropTableId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerChests");
                });

            modelBuilder.Entity("Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ChestDropTable", b =>
                {
                    b.OwnsMany("DropEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChestDropTableId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ItemLevel")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ItemType")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MaxAmount")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MinAmount")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Probability")
                                .HasColumnType("REAL");

                            b1.Property<int>("Rarity")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("SubType")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ChestDropTableId");

                            b1.ToTable("DropEntry");

                            b1.WithOwner()
                                .HasForeignKey("ChestDropTableId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DwarfMiningIdleGame.Server.Entities.GameEntities.PlayerChest", b =>
                {
                    b.HasOne("ChestDropTable", "ChestDropTable")
                        .WithMany()
                        .HasForeignKey("ChestDropTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChestDropTable");

                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
